import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";

import { Theme } from '@radix-ui/themes';
import Providers from "./provider";

export const metadata: Metadata = {
  title: "SR EState",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <Providers>{children}</Providers>
        </Theme>
      </body>
    </html>
  );
}
